### ISSUE TITLE
Bug in implementation of the phase-lag index in `nbt_doPLI` 

### ISSUE THREAD

**Issue by wmayner** [NeurophysiologicalBiomarkerToolbox/NBTpublic#2]
There is a significant problem with the implementation of the phase-lag index in `nbt_doPLI`.

As Stam _et al._ note in [[1]](https://www.ncbi.nlm.nih.gov/pubmed/17266107), the PLI as defined in Eqn. 6 is only valid for phase differences that lie in (–π, π]. Since MATLAB's `angle` function returns phases in that range, the phase _differences_ lie in (–2π, 2π]. 

This means that the `sin` of the phase differences must be taken before the `sign`, since the idea is to determine whether the phase differences are above or below the real axis.

This was also noticed in May 2016 by @NZACH, who submitted a pull request  (#1) fixing the problem.

**Comment by simon-shlomo** [comment]
Hi,

Thank you for reminding us about this bug. It indeed has not yet be merged to the public version of NBT.

**Comment by simon-shlomo** [comment]
This has now been corrected. Thanks for the feedback.

**Comment by GaoxingZheng** [comment]
```
function C = PhaseLagIndex_0911(A)
% Input: A (the 64-channel EEG time series matrix)
% Output: C (the 64*64 phase lag index matrix)
[m,n] = size(A);
diff = zeros(1,n);
y = hilbert(A);
pha = atan2(imag(y),real(y));  % atan（）——inverse tangent
for i2 = 1:m
    for j2 = 1:m
        diff(1,:) = pha(i2,:) - pha(j2,:);
        C(i2,j2) = abs(sum(sign(sin(diff(1,:))))/n); % Choose phase lag index as the brain functional connectivity
    end
end
end
```

**Comment by GaoxingZheng** [comment]
function C = PhaseLagIndex_0911(A)
% Input: A (the 64-channel EEG time series matrix)
% Output: C (the 64*64 phase lag index matrix)
[m,n] = size(A);
diff = zeros(1,n);
y = hilbert(A);
pha = atan2(imag(y),real(y));  % atan（）——inverse tangent
for i2 = 1:m
    for j2 = 1:m
        diff(1,:) = pha(i2,:) - pha(j2,:);
        C(i2,j2) = abs(sum(sign(sin(diff(1,:))))/n); % Choose phase lag index as the brain functional connectivity
    end
end
end
